#client 
#just service and application
#and service is to access the the server
#k3s-demo - k3s-client 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-client
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k3s-client
  template:
    metadata:
      labels:
        app: k3s-client
    spec:
      containers:
      - name: k3s-client
        image: saoirseod/rpi-hostname:latest
        ports: 
        - containerPort: 9000
        #80
---
apiVersion: v1
kind: Service
metadata:
  name: k3s-client
  namespace: default
spec:
  ports:
  - name: http
    targetPort: 9000
    #8000
    #80
    port: 9000
  selector:
    app: k3s-client
